# Generated by Django 3.1.2 on 2020-10-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('is_registered', models.BooleanField()),
                ('date_of_registration', models.DateTimeField()),
            ],
            options={
                'db_table': 'ownership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pots',
            fields=[
                ('pot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=1)),
                ('pot_length', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pot_width', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('pot_height', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('plant', models.CharField(max_length=64)),
                ('plant_type', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'pots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('redemption_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reward_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('redeem_datetime', models.DateTimeField()),
                ('has_been_used', models.BooleanField()),
            ],
            options={
                'db_table': 'redemption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reward', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('points_required', models.IntegerField()),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rewards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=64)),
                ('target_pot', models.IntegerField()),
                ('requester_id', models.IntegerField()),
                ('assignee_id', models.IntegerField(blank=True, null=True)),
                ('points_given', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('datetime_opened', models.DateTimeField()),
                ('is_done', models.BooleanField()),
                ('urgency', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
